-- Package entry point generated by OpenAI Codex on 2026-09-26.
import LieGroups.Manifold.LocalSections
import LieGroups.Manifold.SubmersionLocalSections
import LieGroups.Manifold.SubmersionDifferential
import LieGroups.Manifold.SubmersionCriterion
