/-
Copyright (c) 2026 BFRF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BFRF contributors
-/
import Mathlib.Geometry.Manifold.ContMDiff.Basic

/-!
# Descent of smoothness along maps with local sections

These results concern arbitrary charted spaces and do not depend on brackets or Ricci flow.
Local sections are represented by maps defined everywhere, with regularity and the right-inverse
identity required only near the chosen point. Their existence is a hypothesis here; constructing
them for homogeneous quotient projections is a separate task.

AI-assistance disclosure: this module was generated by OpenAI Codex on 2026-09-24.
-/

open Function Filter
open scoped Topology ContDiff

namespace LieGroups.Manifold

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
  {H' : Type*} [TopologicalSpace H'] {J : ModelWithCorners 𝕜 E' H'}
  {N : Type*} [TopologicalSpace N] [ChartedSpace H' N]
  {E'' : Type*} [NormedAddCommGroup E''] [NormedSpace 𝕜 E'']
  {H'' : Type*} [TopologicalSpace H''] {L : ModelWithCorners 𝕜 E'' H''}
  {P : Type*} [TopologicalSpace P] [ChartedSpace H'' P]
  {n : ℕ∞ω}

/-- A map has `C^n` local sections if near every target point it admits a `C^n` right inverse.
This does not require the map itself to be `C^n`. -/
def HasContMDiffLocalSections (I : ModelWithCorners 𝕜 E H)
    (J : ModelWithCorners 𝕜 E' H') (n : ℕ∞ω) (π : M → N) : Prop :=
  ∀ y : N, ∃ s : N → M, ContMDiffAt J I n s y ∧ (π ∘ s) =ᶠ[𝓝 y] id

namespace HasContMDiffLocalSections

variable {π : M → N} (h : HasContMDiffLocalSections I J n π)

include h

/-- Local right inverses imply surjectivity. -/
theorem surjective : Surjective π := by
  intro y
  obtain ⟨s, _, heq⟩ := h y
  exact ⟨s y, heq.self_of_nhds⟩

/-- A map out of the target is `C^n` whenever its composite with the projection is `C^n`.
This proves the smooth-descent property used by homogeneous quotient interfaces. -/
theorem contMDiff_of_comp {f : N → P} (hf : ContMDiff I L n (f ∘ π)) :
    ContMDiff J L n f := by
  intro y
  obtain ⟨s, hs, heq⟩ := h y
  have hc : ContMDiffAt J L n ((f ∘ π) ∘ s) y := (hf (s y)).comp y hs
  apply hc.congr_of_eventuallyEq
  filter_upwards [heq] with z hz
  exact congrArg f hz.symm

/-- For a `C^n` map with `C^n` local sections, regularity can be checked after composition. -/
theorem contMDiff_iff_comp (hπ : ContMDiff I J n π) {f : N → P} :
    ContMDiff J L n f ↔ ContMDiff I L n (f ∘ π) :=
  ⟨fun hf => hf.comp hπ, h.contMDiff_of_comp⟩

end HasContMDiffLocalSections
end LieGroups.Manifold
