/-
Copyright (c) 2026 Ramiro Lafuente. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ramiro Lafuente
-/
import LieGroups.Manifold.LocalSections
import Mathlib.Analysis.Calculus.InverseFunctionTheorem.ContDiff
import Mathlib.Geometry.Manifold.ContMDiff.NormedSpace
import Mathlib.Topology.Algebra.Module.FiniteDimension

/-!
# Local products and sections from a split-surjective differential

For maps between real or complex normed spaces with complete source, construct a local
product map from a differential with a continuous linear right inverse. Given `ContDiffOn`
on an open set, the map and its inverse are `C^n` throughout their open source and target;
the `ContDiffAt` variants only assert regularity at the specified points. Fixing the kernel
coordinate gives a local section through the prescribed source point. For finite-dimensional
targets, surjectivity of the differential supplies the required right inverse.

These are normed-space results. `SubmersionCriterion.lean` uses the neighborhood version
to construct maximal-atlas charts and prove the manifold differential criterion.

AI-assistance disclosure: this module was generated by OpenAI Codex on 2026-09-27.
-/

open Function Filter
open scoped Topology ContDiff Manifold

namespace LieGroups.Manifold

variable {𝕜 : Type*} [RCLike 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] [CompleteSpace E]
  {F : Type*} [NormedAddCommGroup F] [NormedSpace 𝕜 F]
  {n : ℕ∞ω} {f : E → F} {x : E} {A : E →L[𝕜] F}

/-- The inverse function theorem on open neighborhoods, preserving `C^n` regularity
on the entire source and target, including when `n = ∞`. -/
theorem exists_contDiffOn_localInverse {s : Set E} (hs : IsOpen s) (hx : x ∈ s)
    (hf : ContDiffOn 𝕜 n f s) (L : E ≃L[𝕜] F)
    (hL : HasFDerivAt f (L : E →L[𝕜] F) x) (hn : n ≠ 0) :
    ∃ e : OpenPartialHomeomorph E F, x ∈ e.source ∧ e.source ⊆ s ∧
      (∀ z, e z = f z) ∧ ContDiffOn 𝕜 n e e.source ∧
      ContDiffOn 𝕜 n e.symm e.target := by
  have hfx := hf.contDiffAt (hs.mem_nhds hx)
  let e₀ := hfx.toOpenPartialHomeomorph f hL hn
  have hnear : ∀ᶠ z in 𝓝 x,
      fderiv 𝕜 f z ∈ Set.range (fun e : E ≃L[𝕜] F => (e : E →L[𝕜] F)) := by
    apply (hfx.continuousAt_fderiv hn).preimage_mem_nhds
    rw [hL.fderiv]
    exact L.nhds
  obtain ⟨u, hu, huopen, hxu⟩ := mem_nhds_iff.mp
    (Filter.inter_mem (hs.mem_nhds hx) hnear)
  let e := e₀.restr u
  have hsource : ∀ z ∈ e.source, z ∈ s ∧
      fderiv 𝕜 f z ∈ Set.range (fun e : E ≃L[𝕜] F => (e : E →L[𝕜] F)) := by
    intro z hz
    exact hu (huopen.interior_eq ▸ hz.2)
  have he : ∀ z, e z = f z := fun _ => rfl
  have hforward : ∀ z ∈ e.source, ContDiffAt 𝕜 n e z := by
    intro z hz
    exact hf.contDiffAt (hs.mem_nhds (hsource z hz).1)
  refine ⟨e, ?_, fun z hz => (hsource z hz).1, he,
    fun z hz => (hforward z hz).contDiffWithinAt, ?_⟩
  · exact ⟨hfx.mem_toOpenPartialHomeomorph_source hL hn, by simpa [huopen.interior_eq]⟩
  · intro y hy
    have hz := e.map_target hy
    obtain ⟨L', hL'⟩ := (hsource (e.symm y) hz).2
    change (L' : E →L[𝕜] F) = fderiv 𝕜 f (e.symm y) at hL'
    have hd : HasFDerivAt e (L' : E →L[𝕜] F) (e.symm y) := by
      rw [hL']
      exact ((hforward _ hz).differentiableAt hn).hasFDerivAt
    exact (e.contDiffAt_symm hy hd (hforward _ hz)).contDiffWithinAt

/-- A split-surjective differential gives product coordinates that are `C^n`
throughout their open source and target, when the original map is `C^n` on an open set. -/
theorem exists_contDiffOn_localProduct_of_rightInverse {s : Set E}
    (hs : IsOpen s) (hx : x ∈ s) (hf : ContDiffOn 𝕜 n f s)
    (hA : HasFDerivAt f A x) (hn : n ≠ 0)
    (R : F →L[𝕜] E) (hR : RightInverse R A) :
    ∃ e : OpenPartialHomeomorph E (F × A.ker),
      x ∈ e.source ∧ e.source ⊆ s ∧
      (∀ z, e z = (f z, A.projKerOfRightInverse R hR z)) ∧
      ContDiffOn 𝕜 n e e.source ∧ ContDiffOn 𝕜 n e.symm e.target ∧
      ∀ y ∈ e.target, f (e.symm y) = y.1 := by
  let L := ContinuousLinearEquiv.equivOfRightInverse A R hR
  let P := A.projKerOfRightInverse R hR
  have hg : ContDiffOn 𝕜 n (fun z => (f z, P z)) s := hf.prodMk P.contDiff.contDiffOn
  obtain ⟨e, hx, hsub, he, hforward, hinverse⟩ :=
    exists_contDiffOn_localInverse hs hx hg L (hA.prodMk P.hasFDerivAt) hn
  refine ⟨e, hx, hsub, he, hforward, hinverse, ?_⟩
  intro y hy
  have h := congrArg Prod.fst (e.right_inv hy)
  simpa only [he] using h

/-- A split-surjective differential gives local product coordinates, with `C^n`
regularity of the coordinates and their inverse at the base points. The first coordinate
is the original map, and the second coordinate is the projection onto the kernel. -/
theorem exists_contDiffAt_localProduct_of_rightInverse
    (hf : ContDiffAt 𝕜 n f x) (hA : HasFDerivAt f A x) (hn : n ≠ 0)
    (R : F →L[𝕜] E) (hR : RightInverse R A) :
    ∃ e : OpenPartialHomeomorph E (F × A.ker),
      x ∈ e.source ∧
      (∀ z, e z = (f z, A.projKerOfRightInverse R hR z)) ∧
      ContDiffAt 𝕜 n e x ∧ ContDiffAt 𝕜 n e.symm (e x) ∧
      ∀ y ∈ e.target, f (e.symm y) = y.1 := by
  let L := ContinuousLinearEquiv.equivOfRightInverse A R hR
  let P := A.projKerOfRightInverse R hR
  let g : E → F × A.ker := fun z => (f z, P z)
  have hg : ContDiffAt 𝕜 n g x := hf.prodMk P.contDiff.contDiffAt
  have hg' : HasFDerivAt g (L : E →L[𝕜] F × A.ker) x :=
    hA.prodMk P.hasFDerivAt
  let e := hg.toOpenPartialHomeomorph g hg' hn
  refine ⟨e, hg.mem_toOpenPartialHomeomorph_source hg' hn, fun _ => rfl,
    hg, ?_, ?_⟩
  · exact hg.to_localInverse hg' hn
  · intro y hy
    exact congrArg Prod.fst (e.right_inv hy)

/-- A `C^n` map with a split-surjective differential has a local `C^n` section
through the given source point. Only the source normed space must be complete. -/
theorem exists_contDiffAt_localSection_of_rightInverse
    (hf : ContDiffAt 𝕜 n f x) (hA : HasFDerivAt f A x) (hn : n ≠ 0)
    (R : F →L[𝕜] E) (hR : RightInverse R A) :
    ∃ s : F → E, s (f x) = x ∧ ContDiffAt 𝕜 n s (f x) ∧
      (f ∘ s) =ᶠ[𝓝 (f x)] id := by
  obtain ⟨e, hx, he, _, hi, hfst⟩ :=
    exists_contDiffAt_localProduct_of_rightInverse hf hA hn R hR
  let lift : F → F × A.ker := fun y => (y, (e x).2)
  have hlift : lift (f x) = e x := by simp [lift, he]
  have hl : ContDiffAt 𝕜 n lift (f x) := contDiffAt_id.prodMk contDiffAt_const
  refine ⟨e.symm ∘ lift, ?_, ?_, ?_⟩
  · simpa only [comp_apply, hlift] using e.left_inv hx
  · exact (hlift ▸ hi).comp (f x) hl
  · have hnear : ∀ᶠ y in 𝓝 (f x), lift y ∈ e.target :=
      hl.continuousAt.preimage_mem_nhds
        (hlift ▸ e.open_target.mem_nhds (e.map_source hx))
    filter_upwards [hnear] with y hy
    exact hfst (lift y) hy

/-- For finite-dimensional targets, a surjective differential suffices to obtain
a local section. This includes maps between finite-dimensional real normed spaces. -/
theorem exists_contDiffAt_localSection_of_surjective
    [FiniteDimensional 𝕜 F]
    (hf : ContDiffAt 𝕜 n f x) (hA : HasFDerivAt f A x) (hn : n ≠ 0)
    (h_surj : Surjective A) :
    ∃ s : F → E, s (f x) = x ∧ ContDiffAt 𝕜 n s (f x) ∧
      (f ∘ s) =ᶠ[𝓝 (f x)] id := by
  obtain ⟨R, hR⟩ := A.exists_rightInverse_of_surjective
    (LinearMap.range_eq_top.mpr h_surj)
  apply exists_contDiffAt_localSection_of_rightInverse hf hA hn R
  intro y
  exact DFunLike.congr_fun hR y

/-- A surjective `C^n` map of normed spaces whose differential has a continuous linear
right inverse at every point has local sections in the smooth-descent interface. -/
theorem hasContMDiffLocalSections_of_surjective_splitDifferential
    (hf : ContDiff 𝕜 n f) (hn : n ≠ 0) (h_surj : Surjective f)
    (hsplit : ∀ x, ∃ R : F →L[𝕜] E, RightInverse R (fderiv 𝕜 f x)) :
    HasContMDiffLocalSections 𝓘(𝕜, E) 𝓘(𝕜, F) n f := by
  intro y
  obtain ⟨x, rfl⟩ := h_surj y
  obtain ⟨R, hR⟩ := hsplit x
  obtain ⟨s, _, hs, heq⟩ := exists_contDiffAt_localSection_of_rightInverse
    hf.contDiffAt ((hf.differentiable hn x).hasFDerivAt) hn R hR
  exact ⟨s, hs.contMDiffAt, heq⟩

/-- A surjective `C^n` map to a finite-dimensional normed space with surjective
differentials admits local sections, so the existing smooth-descent theorems apply. -/
theorem hasContMDiffLocalSections_of_surjective_differential
    [FiniteDimensional 𝕜 F]
    (hf : ContDiff 𝕜 n f) (hn : n ≠ 0) (h_surj : Surjective f)
    (hderiv : ∀ x, Surjective (fderiv 𝕜 f x)) :
    HasContMDiffLocalSections 𝓘(𝕜, E) 𝓘(𝕜, F) n f := by
  apply hasContMDiffLocalSections_of_surjective_splitDifferential hf hn h_surj
  intro x
  obtain ⟨R, hR⟩ := (fderiv 𝕜 f x).exists_rightInverse_of_surjective
    (LinearMap.range_eq_top.mpr (hderiv x))
  exact ⟨R, fun y => DFunLike.congr_fun hR y⟩

end LieGroups.Manifold
