/-
Copyright (c) 2026 Ramiro Lafuente. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ramiro Lafuente
-/
import LieGroups.Manifold.SubmersionDifferential
import LieGroups.Manifold.SubmersionLocalSections
import Mathlib.Geometry.Manifold.MFDeriv.Basic

/-!
# Differential criterion for submersions without boundary

Construct submersion charts from a continuous linear right inverse to the differential.
The source model space is complete and boundaryless, and the scalar field is real or complex.
The original map is `C^n` on the manifold, with `n ≠ 0`.

Classical anchors: Lee, *Introduction to Smooth Manifolds*, second edition (2013),
Theorem 4.12, p. 81 (the submersion case), and Theorem 4.26, p. 88 (the forward direction).
See `docs/FOUNDATIONS.md` for the statement comparison and checked references.

AI-assistance disclosure: generated by OpenAI Codex on 2026-09-27.
-/

open Function Filter Set
open scoped Topology ContDiff Manifold

namespace LieGroups.Manifold

variable {𝕜 : Type*} [RCLike 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] [CompleteSpace E]
  {F : Type*} [NormedAddCommGroup F] [NormedSpace 𝕜 F]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H} [I.Boundaryless]
  {H' : Type*} [TopologicalSpace H'] {J : ModelWithCorners 𝕜 F H'}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  {N : Type*} [TopologicalSpace N] [ChartedSpace H' N]
  {n : ℕ∞ω} [IsManifold I n M] [IsManifold J n N]

omit [CompleteSpace E] [IsManifold J n N] in
private theorem isSubmersionAt_of_localProductChart
    {K : Type*} [NormedAddCommGroup K] [NormedSpace 𝕜 K]
    {f : M → N} {x : M} (hf : ContinuousAt f x)
    (c : OpenPartialHomeomorph M E) (d : OpenPartialHomeomorph N H')
    (hx : x ∈ c.source) (hfx : f x ∈ d.source)
    (hc : ContMDiffOn I 𝓘(𝕜, E) n c c.source)
    (hci : ContMDiffOn 𝓘(𝕜, E) I n c.symm c.target)
    (hd : d ∈ IsManifold.maximalAtlas J n N)
    (L : E ≃L[𝕜] F × K)
    (heq : EqOn ((d.extend J) ∘ f ∘ c.symm) (Prod.fst ∘ L) c.target) :
    _root_.Manifold.IsSubmersionAt I J n f x := by
  let φ := c.trans I.toHomeomorph.symm.toOpenPartialHomeomorph
  have hIsymm : ContMDiff 𝓘(𝕜, E) I n I.symm := by
    simpa only [I.range_eq_univ, contMDiffOn_univ] using I.contMDiffOn_symm (n := n)
  have hφ : φ ∈ IsManifold.maximalAtlas I n M := by
    apply φ.mem_maximalAtlas_of_contMDiffOn
    · exact (hIsymm.comp_contMDiffOn hc).mono (fun _ hz => hz.1)
    · exact hci.comp (I.contMDiff.contMDiffOn) (fun _ hz => hz.2)
  apply _root_.Manifold.IsSubmersionAtOfComplement.isSubmersionAt
    (_root_.Manifold.IsSubmersionAtOfComplement.mk_of_continuousAt hf L φ d
      ⟨hx, mem_univ _⟩ hfx hφ hd ?_)
  intro z hz
  have hz' : I.symm z ∈ φ.target := (φ.extend_target (I := I) ▸ hz).1
  have hIz : I (I.symm z) = z := I.right_inv ((φ.extend_target (I := I) ▸ hz).2)
  have hcz : z ∈ c.target := by
    have : I (I.symm z) ∈ c.target := hz'.2
    rwa [hIz] at this
  change (d.extend J) (f (c.symm (I (I.symm z)))) = (L z).1
  rw [hIz]
  exact heq hcz

/-- A `C^n` map from a boundaryless manifold is a submersion at a point if its
differential there has a continuous linear right inverse. The source model is complete. -/
theorem isSubmersionAt_of_rightInverse_mfderiv {f : M → N} {x : M}
    (hf : ContMDiff I J n f) (hn : n ≠ 0)
    (R : TangentSpace J (f x) →L[𝕜] TangentSpace I x)
    (hR : RightInverse R (mfderiv I J f x)) :
    _root_.Manifold.IsSubmersionAt I J n f x := by
  let a : OpenPartialHomeomorph M E :=
    { toPartialEquiv := extChartAt I x
      open_source := isOpen_extChartAt_source x
      open_target := isOpen_extChartAt_target x
      continuousOn_toFun := continuousOn_extChartAt x
      continuousOn_invFun := continuousOn_extChartAt_symm x }
  let b := extChartAt J (f x)
  let g : E → F := b ∘ f ∘ a.symm
  let s : Set E := a.target ∩ a.symm ⁻¹' (f ⁻¹' b.source)
  have hs : IsOpen s := a.isOpen_inter_preimage_symm
    ((isOpen_extChartAt_source (f x)).preimage hf.continuous)
  have hax : x ∈ a.source := mem_extChartAt_source x
  have hx : a x ∈ s := ⟨a.map_source hax, by
    change f (a.symm (a x)) ∈ b.source
    rw [a.left_inv hax]
    exact mem_extChartAt_source (f x)⟩
  have ha : ContMDiffOn I 𝓘(𝕜, E) n a a.source := by
    change ContMDiffOn I 𝓘(𝕜, E) n (extChartAt I x) (extChartAt I x).source
    simpa only [extChartAt_source] using (contMDiffOn_extChartAt (I := I) (x := x) (n := n))
  have hai : ContMDiffOn 𝓘(𝕜, E) I n a.symm a.target :=
    contMDiffOn_extChartAt_symm x
  have hg : ContDiffOn 𝕜 n g s := by
    apply ContMDiffOn.contDiffOn
    have hb : ContMDiffOn J 𝓘(𝕜, F) n b b.source := by
      simpa only [b, extChartAt_source] using
        (contMDiffOn_extChartAt (I := J) (x := f x) (n := n))
    exact hb.comp (hf.comp_contMDiffOn (hai.mono inter_subset_left)) (fun _ hz => hz.2)
  let A : E →L[𝕜] F := (tangentSpaceCastModel J (f x)).toContinuousLinearMap ∘L
    mfderiv I J f x ∘L (tangentSpaceCastModel I x).symm.toContinuousLinearMap
  let S : F →L[𝕜] E := (tangentSpaceCastModel I x).toContinuousLinearMap ∘L
    R ∘L (tangentSpaceCastModel J (f x)).symm.toContinuousLinearMap
  have hA : HasFDerivAt g A (a x) := by
    have hd := ((hf x).mdifferentiableAt hn).hasMFDerivAt.2
    rw [I.range_eq_univ, hasFDerivWithinAt_univ] at hd
    exact hd
  have hS : RightInverse S A := by
    intro y
    simp only [A, S, ContinuousLinearMap.comp_apply, ContinuousLinearEquiv.coe_coe,
      ContinuousLinearEquiv.symm_apply_apply, hR _, ContinuousLinearEquiv.apply_symm_apply]
  let L := ContinuousLinearEquiv.equivOfRightInverse A S hS
  obtain ⟨p, hpx, hps, _, hpf, hpi, hnormal⟩ :=
    exists_contDiffOn_localProduct_of_rightInverse hs hx hg hA hn S hS
  let c := (a.trans p).trans L.symm.toHomeomorph.toOpenPartialHomeomorph
  have hc : ContMDiffOn I 𝓘(𝕜, E) n c c.source := by
    have hcomp := hpf.contMDiffOn.comp (ha.mono (inter_subset_left)) (fun _ hz => hz.2)
    exact (L.symm.contDiff.contMDiff.comp_contMDiffOn hcomp).mono (fun _ hz => hz.1)
  have hci : ContMDiffOn 𝓘(𝕜, E) I n c.symm c.target := by
    have hcomp := hai.comp hpi.contMDiffOn (fun z hz => (hps (p.map_target hz)).1)
    exact hcomp.comp L.contDiff.contMDiff.contMDiffOn (fun _ hz => hz.2.1)
  apply isSubmersionAt_of_localProductChart hf.continuous.continuousAt c (chartAt H' (f x))
    ⟨⟨hax, hpx⟩, mem_univ _⟩ (mem_chart_source _ _) hc hci
    (IsManifold.chart_mem_maximalAtlas _) L
  intro z hz
  exact hnormal (L z) hz.2.1

/-- For a finite-dimensional target model, surjectivity of the differential implies
the submersion normal form. In particular this applies to finite-dimensional real manifolds. -/
theorem isSubmersionAt_of_surjective_mfderiv [FiniteDimensional 𝕜 F]
    {f : M → N} {x : M} (hf : ContMDiff I J n f) (hn : n ≠ 0)
    (hderiv : Surjective (mfderiv I J f x)) :
    _root_.Manifold.IsSubmersionAt I J n f x := by
  let : T2Space (TangentSpace J (f x)) :=
    (tangentSpaceCastModel J (f x)).symm.toHomeomorph.t2Space
  let : FiniteDimensional 𝕜 (TangentSpace J (f x)) :=
    (tangentSpaceCastModel J (f x)).symm.toLinearEquiv.finiteDimensional
  obtain ⟨R, hR⟩ := (mfderiv I J f x).exists_rightInverse_of_surjective
    (LinearMap.range_eq_top.mpr hderiv)
  exact isSubmersionAt_of_rightInverse_mfderiv hf hn R (fun y => DFunLike.congr_fun hR y)

/-- The differential criterion gives a local `C^n` section through any prescribed
source point, for maps from a boundaryless manifold with finite-dimensional target model. -/
theorem exists_contMDiffAt_localSection_of_surjective_mfderiv [FiniteDimensional 𝕜 F]
    {f : M → N} {x : M} (hf : ContMDiff I J n f) (hn : n ≠ 0)
    (hderiv : Surjective (mfderiv I J f x)) :
    ∃ s : N → M, s (f x) = x ∧ ContMDiffAt J I n s (f x) ∧
      (f ∘ s) =ᶠ[𝓝 (f x)] id :=
  exists_contMDiffAt_localSection_of_isSubmersionAt
    (isSubmersionAt_of_surjective_mfderiv hf hn hderiv)

/-- A surjective `C^n` map with split-surjective differentials has local sections
everywhere, supplying the smooth-descent interface on boundaryless manifolds. -/
theorem hasContMDiffLocalSections_of_surjective_split_mfderiv
    {f : M → N} (hf : ContMDiff I J n f) (hn : n ≠ 0) (h_surj : Surjective f)
    (hsplit : ∀ x, ∃ R : TangentSpace J (f x) →L[𝕜] TangentSpace I x,
      RightInverse R (mfderiv I J f x)) :
    HasContMDiffLocalSections I J n f := by
  apply hasContMDiffLocalSections_of_surjective_submersion h_surj
  intro x
  obtain ⟨R, hR⟩ := hsplit x
  exact isSubmersionAt_of_rightInverse_mfderiv hf hn R hR

/-- A surjective `C^n` map with surjective differentials and finite-dimensional target
has local sections everywhere. Hence smoothness of maps out of its target descends. -/
theorem hasContMDiffLocalSections_of_surjective_mfderiv [FiniteDimensional 𝕜 F]
    {f : M → N} (hf : ContMDiff I J n f) (hn : n ≠ 0) (h_surj : Surjective f)
    (hderiv : ∀ x, Surjective (mfderiv I J f x)) :
    HasContMDiffLocalSections I J n f :=
  hasContMDiffLocalSections_of_surjective_submersion h_surj
    (fun x => isSubmersionAt_of_surjective_mfderiv hf hn (hderiv x))

end LieGroups.Manifold
