/-
Copyright (c) 2026 BFRF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BFRF contributors
-/
import LieGroups.Manifold.LocalSections
import Mathlib.Geometry.Manifold.Submersion

/-!
# Local sections of submersions

Construct local right inverses from Mathlib's chart-normal-form definition of a submersion.
The source model is boundaryless; no finite-dimensionality or completeness is needed for
this consequence of the normal form. Deriving that normal form from a surjective differential
is a separate theorem.

Classical statement anchor: Lee, *Introduction to Smooth Manifolds*, second edition,
the discussion of submersions and local sections. We use Mathlib's definition and prove the
normal-form consequence directly, rather than assuming the classical theorem.

AI-assistance disclosure: this module was generated by OpenAI Codex on 2026-09-26.
-/

open Function Filter
open scoped Topology ContDiff Manifold

namespace LieGroups.Manifold

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
  {H' : Type*} [TopologicalSpace H'] {J : ModelWithCorners 𝕜 E' H'}
  {N : Type*} [TopologicalSpace N] [ChartedSpace H' N]
  {n : ℕ∞ω} [I.Boundaryless]

/-- A submersion in chart normal form has a local `C^n` section through the given point.
The section is a total function, but its regularity and right-inverse identity are local. -/
theorem exists_contMDiffAt_localSection_of_isSubmersionAt {π : M → N} {x : M}
    (h : _root_.Manifold.IsSubmersionAt I J n π x) :
    ∃ s : N → M, s (π x) = x ∧ ContMDiffAt J I n s (π x) ∧
      (π ∘ s) =ᶠ[𝓝 (π x)] id := by
  let a := h.domChart.extend I
  let b := h.codChart.extend J
  have hx : x ∈ a.source := by simpa [a] using h.mem_domChart_source
  have hπx : π x ∈ b.source := by simpa [b] using h.mem_codChart_source
  have ha : a x ∈ a.target := a.map_source hx
  have hfirst : b (π x) = (h.equiv (a x)).1 := by
    have hw := h.writtenInCharts ha
    change b (π (a.symm (a x))) = (h.equiv (a x)).1 at hw
    rwa [a.left_inv hx] at hw
  let c := (h.equiv (a x)).2
  let lift : N → E := fun y => h.equiv.symm (b y, c)
  have hlift : lift (π x) = a x := by
    dsimp [lift, c]
    rw [hfirst, Prod.eta, h.equiv.symm_apply_apply]
  have hb : ContMDiffAt J 𝓘(𝕜, E') n b (π x) :=
    h.codChart.contMDiffAt_extend h.codChart_mem_maximalAtlas h.mem_codChart_source
  have hl : ContMDiffAt J 𝓘(𝕜, E) n lift (π x) := by
    have hlin : ContMDiff 𝓘(𝕜, E' × h.complement) 𝓘(𝕜, E) n h.equiv.symm := by
      rw [contMDiff_iff_contDiff]
      fun_prop
    exact hlin.contMDiffAt.comp (π x) (hb.prodMk_space contMDiffAt_const)
  have hopen : IsOpen a.target := h.domChart.isOpen_extend_target
  have hsmooth : ContMDiffAt 𝓘(𝕜, E) I n a.symm (lift (π x)) := by
    rw [hlift]
    apply (contMDiffOn_extend_symm h.domChart_mem_maximalAtlas).contMDiffAt
    simpa only [← h.domChart.extend_target'] using hopen.mem_nhds ha
  refine ⟨a.symm ∘ lift, ?_, hsmooth.comp (π x) hl, ?_⟩
  · simpa only [comp_apply, hlift] using a.left_inv hx
  have hnear : ∀ᶠ y in 𝓝 (π x), lift y ∈ a.target :=
    hl.continuousAt.preimage_mem_nhds (hlift ▸ hopen.mem_nhds ha)
  have hbnear : ∀ᶠ y in 𝓝 (π x), y ∈ b.source :=
    h.codChart.isOpen_extend_source.mem_nhds hπx
  filter_upwards [hnear, hbnear] with y hy hby
  have hsource : a.symm (lift y) ∈ h.domChart.source := by
    simpa only [a, h.domChart.extend_source] using a.map_target hy
  have htarget : π (a.symm (lift y)) ∈ b.source := by
    change π (a.symm (lift y)) ∈ (h.codChart.extend J).source
    rw [h.codChart.extend_source]
    exact h.source_subset_preimage_source hsource
  apply b.injOn htarget hby
  have hw := h.writtenInCharts hy
  change b (π (a.symm (lift y))) = (h.equiv (lift y)).1 at hw
  simpa only [lift, h.equiv.apply_symm_apply] using hw

/-- A surjective map that is a submersion at every point admits local `C^n` sections. -/
theorem hasContMDiffLocalSections_of_surjective_submersion {π : M → N}
    (hπ : Surjective π) (hsub : ∀ x, _root_.Manifold.IsSubmersionAt I J n π x) :
    HasContMDiffLocalSections I J n π := by
  intro y
  obtain ⟨x, rfl⟩ := hπ y
  obtain ⟨s, _, hs, heq⟩ := exists_contMDiffAt_localSection_of_isSubmersionAt (hsub x)
  exact ⟨s, hs, heq⟩

end LieGroups.Manifold
