import LieGroups.Manifold.LocalSections
import LieGroups.Manifold.SubmersionLocalSections

/-!
# Foundations axiom report

AI-generation disclosure: generated by OpenAI Codex on 2026-09-24; updated on 2026-09-26.
Run `lake env lean scripts/AuditFoundations.lean` after `lake build`.
This reports dependencies; it neither enforces an allowlist nor proves hypotheses inhabited.
-/

#print axioms LieGroups.Manifold.HasContMDiffLocalSections.surjective
#print axioms LieGroups.Manifold.HasContMDiffLocalSections.contMDiff_of_comp
#print axioms LieGroups.Manifold.HasContMDiffLocalSections.contMDiff_iff_comp
#print axioms LieGroups.Manifold.exists_contMDiffAt_localSection_of_isSubmersionAt
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_submersion
