import LieGroups.Manifold.LocalSections
import LieGroups.Manifold.SubmersionLocalSections
import LieGroups.Manifold.SubmersionDifferential
import LieGroups.Manifold.SubmersionCriterion

/-!
# Foundations axiom report

AI-generation disclosure: generated by OpenAI Codex on 2026-09-24; updated on 2026-09-27.
Run `lake env lean scripts/AuditFoundations.lean` after `lake build`.
This reports dependencies; it neither enforces an allowlist nor proves hypotheses inhabited.
-/

#print axioms LieGroups.Manifold.HasContMDiffLocalSections.surjective
#print axioms LieGroups.Manifold.HasContMDiffLocalSections.contMDiff_of_comp
#print axioms LieGroups.Manifold.HasContMDiffLocalSections.contMDiff_iff_comp
#print axioms LieGroups.Manifold.exists_contMDiffAt_localSection_of_isSubmersionAt
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_submersion
#print axioms LieGroups.Manifold.exists_contDiffAt_localProduct_of_rightInverse
#print axioms LieGroups.Manifold.exists_contDiffAt_localSection_of_rightInverse
#print axioms LieGroups.Manifold.exists_contDiffAt_localSection_of_surjective
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_splitDifferential
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_differential
#print axioms LieGroups.Manifold.exists_contDiffOn_localInverse
#print axioms LieGroups.Manifold.exists_contDiffOn_localProduct_of_rightInverse
#print axioms LieGroups.Manifold.isSubmersionAt_of_rightInverse_mfderiv
#print axioms LieGroups.Manifold.isSubmersionAt_of_surjective_mfderiv
#print axioms LieGroups.Manifold.exists_contMDiffAt_localSection_of_surjective_mfderiv
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_split_mfderiv
#print axioms LieGroups.Manifold.hasContMDiffLocalSections_of_surjective_mfderiv
