import LieGroups
import Mathlib.Geometry.Manifold.MFDeriv.FDeriv
import Mathlib.Analysis.Calculus.FDeriv.Pow

/-!
# Nonlinear example for the differential criterion

The map `(u, v) ↦ u + v²` has positive-dimensional fibers. Check that the manifold
criterion constructs normal forms, sections through arbitrary points, and smooth descent.
Run `lake env lean scripts/CheckSubmersionCriterion.lean` after `lake build`.

AI-assistance disclosure: generated by OpenAI Codex on 2026-09-27.
-/

open Function Filter LieGroups.Manifold
open scoped Topology ContDiff Manifold

namespace SubmersionCriterionCheck

def quadraticProjection (p : ℝ × ℝ) : ℝ := p.1 + p.2 ^ 2

theorem quadraticProjection_contDiff : ContDiff ℝ ∞ quadraticProjection := by
  unfold quadraticProjection
  fun_prop

theorem quadraticProjection_hasFDerivAt (p : ℝ × ℝ) :
    HasFDerivAt quadraticProjection
      (ContinuousLinearMap.fst ℝ ℝ ℝ + (2 * p.2) • ContinuousLinearMap.snd ℝ ℝ ℝ) p := by
  convert!
    (hasFDerivAt_fst (𝕜 := ℝ) (p := p)).add ((hasFDerivAt_snd (𝕜 := ℝ) (p := p)).pow 2)
    using 1
  simp

theorem quadraticProjection_surjective_mfderiv (p : ℝ × ℝ) :
    Surjective (mfderiv 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ) quadraticProjection p) := by
  rw [mfderiv_eq_fderiv]
  change Surjective (fderiv ℝ quadraticProjection p : ℝ × ℝ → ℝ)
  rw [(quadraticProjection_hasFDerivAt p).fderiv]
  intro y
  exact ⟨(y, 0), by simp⟩

example (p : ℝ × ℝ) :
    _root_.Manifold.IsSubmersionAt 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ) ∞ quadraticProjection p :=
  isSubmersionAt_of_surjective_mfderiv quadraticProjection_contDiff.contMDiff (by simp)
    (quadraticProjection_surjective_mfderiv p)

example (p : ℝ × ℝ) : ∃ s : ℝ → ℝ × ℝ,
    s (quadraticProjection p) = p ∧ ContMDiffAt 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ × ℝ) ∞ s
      (quadraticProjection p) ∧ (quadraticProjection ∘ s) =ᶠ[𝓝 (quadraticProjection p)] id :=
  exists_contMDiffAt_localSection_of_surjective_mfderiv
    quadraticProjection_contDiff.contMDiff (by simp) (quadraticProjection_surjective_mfderiv p)

theorem quadraticProjection_localSections :
    HasContMDiffLocalSections 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, ℝ) ∞ quadraticProjection := by
  apply hasContMDiffLocalSections_of_surjective_mfderiv
    quadraticProjection_contDiff.contMDiff (by simp) ?_ quadraticProjection_surjective_mfderiv
  intro y
  exact ⟨(y, 0), by simp [quadraticProjection]⟩

example (g : ℝ → ℝ) :
    ContDiff ℝ ∞ g ↔ ContDiff ℝ ∞ (g ∘ quadraticProjection) := by
  simpa only [contMDiff_iff_contDiff] using
    quadraticProjection_localSections.contMDiff_iff_comp
      quadraticProjection_contDiff.contMDiff (L := 𝓘(ℝ, ℝ)) (f := g)

end SubmersionCriterionCheck
